# Generated by Django 4.1.3 on 2023-09-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_album_slug_track_slug_alter_album_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenblacklist',
            old_name='TOKEN',
            new_name='token',
        ),
    ]
