# Generated by Django 4.1.3 on 2023-09-17 18:46

import api.models.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_token_tokenblacklist_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(storage=api.models.storage.UUIDStorage(), upload_to='images/albums/'),
        ),
        migrations.AlterField(
            model_name='singletrack',
            name='cover_image',
            field=models.ImageField(storage=api.models.storage.UUIDStorage(), upload_to='images/tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(storage=api.models.storage.UUIDStorage(), upload_to='files/tracks/'),
        ),
    ]
