# Generated by Django 4.1.3 on 2023-09-18 22:02

import api.models.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_album_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(default='/images/profiles/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(default='/images/albums/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/albums/'),
        ),
        migrations.AlterField(
            model_name='singletrack',
            name='cover_image',
            field=models.ImageField(default='/images/tracks/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/tracks/'),
        ),
    ]
