# Generated by Django 4.1.3 on 2023-09-19 06:13

import api.models.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_singletrack_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(default='/images/profiles/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/artists/'),
        ),
        migrations.AlterField(
            model_name='singletrack',
            name='cover_image',
            field=models.ImageField(default='/images/tracks/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/tracks/'),
        ),
    ]
