# Generated by Django 4.1.3 on 2023-09-22 11:23

import api.models.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_album_cover_image_alter_artist_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(default='/home/tunny/Desktop/soundscape/backend/uploads/images/artists/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/artists/'),
        ),
    ]
