# Generated by Django 4.1.3 on 2023-09-22 11:33

import api.models.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_artist_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(default='/home/tunny/Desktop/soundscape/backend/uploads/images/albums/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/albums/'),
        ),
        migrations.AlterField(
            model_name='singletrack',
            name='cover_image',
            field=models.ImageField(default='/home/tunny/Desktop/soundscape/backend/uploads/images/tracks/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/tracks/'),
        ),
    ]
