# Generated by Django 4.2.5 on 2023-09-28 23:59

import api.models.storage
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_album_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(default='images/albums/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/albums/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(default='images/artists/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/artists/'),
        ),
        migrations.AlterField(
            model_name='singletrack',
            name='cover_image',
            field=models.ImageField(default='images/tracks/default.jpg', storage=api.models.storage.UUIDStorage(), upload_to='images/tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
